services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-quanta
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
      - ./ollama/init:/init
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: [ "/bin/sh", "/init/run_ollama.sh" ]

  db:
    build:
      context: ./db
    container_name: db-quanta
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=not-secure
      - POSTGRES_DB=quanta
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.with-build
    container_name: backend-quanta
    depends_on:
      - db
      - ollama
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/quanta
      - QUARKUS_DATASOURCE_USERNAME=webapp
      - QUARKUS_DATASOURCE_PASSWORD=not-secure
      - OLLAMA_HOST=http://ollama:11434
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE-URL=http://ollama-quanta:11434
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-quanta
    depends_on:
      - backend
    ports:
      - "3000:80"